### ISSUE TITLE
OpenShot (git clone 2016-10-20) fails to launch (Ubuntu 16.04.1)

### ISSUE THREAD

**Issue by clockworkpc** [OpenShot/openshot-qt#381]
Steps taken:
- [ ] Cloned from git.
- [ ] Installed.
- [ ] Ran, but OpenShot failed to launch.
- [ ] Had to CTRL-C.

From logger:
      logger:ERROR module 'openshot' has no attribute 'CacheMemory'

clockworkpc@clockworkpc-Inspiron-7720:~/Downloads/openshot-qt$ openshot-qt
Loaded modules from installed directory: /usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.1.0-dev1)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.1.0-dev1
         app:INFO libopenshot version: 0.1.2
         app:INFO platform: Linux-4.4.0-42-generic-x86_64-with-Ubuntu-16.04-xenial
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.5.2
         app:INFO qt5 version: 5.5.1
         app:INFO pyqt5 version: 5.5.1
    language:INFO Qt Detected Languages: ['en-AU', 'en']
    language:INFO LANG Environment Variable: en_AU.UTF-8
    language:INFO LOCALE Environment Variable: en_AU
    language:INFO Attempting to load qt_en_AU.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_en in '/usr/share/qt5/translations'
    language:INFO Attempting to load qtbase_en_AU.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load qtbase_en in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_en_AU.UTF-8 in '/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/locale/QT'
    language:INFO Attempting to load qt_en in '/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_en_AU.UTF-8 in '/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_en in '/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/locale/QT'
    language:INFO Attempting to load en_AU.UTF-8/LC_MESSAGES/OpenShot in '/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/locale'
    language:INFO Attempting to load en/LC_MESSAGES/OpenShot in '/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/locale'
    language:INFO Attempting to load qt_en_AU in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_en in '/usr/share/qt5/translations'
    language:INFO Attempting to load qtbase_en_AU in '/usr/share/qt5/translations'
    language:INFO Attempting to load qtbase_en in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_en_AU in '/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/locale/QT'
    language:INFO Attempting to load qt_en in '/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_en_AU in '/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/locale/QT'
    language:INFO Attempting to load qtbase_en in '/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/locale/QT'
    language:INFO Attempting to load en_AU/LC_MESSAGES/OpenShot in '/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/locale'
    language:INFO Successfully loaded en_AU/LC_MESSAGES/OpenShot in '/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/locale'
    language:INFO Exiting translation system (since we successfully loaded: en_AU)
project_data:INFO Setting default profile to HDV 720 24p
         app:INFO Setting font to /usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
    language:INFO Attempting to load qt_en_AU.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_en in '/usr/share/qt5/translations'
    language:INFO Attempting to load en_AU.UTF-8/LC_MESSAGES/OpenShot in '/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/locale'
    language:INFO Attempting to load en/LC_MESSAGES/OpenShot in '/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/locale'
    language:INFO Attempting to load qt_en_AU in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_en in '/usr/share/qt5/translations'
    language:INFO Attempting to load en_AU/LC_MESSAGES/OpenShot in '/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/locale'
    language:INFO Successfully loaded en_AU/LC_MESSAGES/OpenShot in '/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/locale'
link SVGID_18_-5 hasn't been detected!
link SVGID_18_-5 hasn't been detected!
link SVGID_22_-5 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
link SVGID_24_-2 hasn't been detected!
     metrics:INFO Track metric: {'status': '200', 'date': 'Wed, 12 Oct 2016 10:38:12 GMT', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'content-length': '35', 'x-content-type-options': 'nosniff', 'age': '640874', 'cache-control': 'no-cache, no-store, must-revalidate', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'content-location': 'http://www.google-analytics.com/collect?ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&cd=main-screen&an=OpenShot+Video+Editor&cd1=0.1.2&v=1&cd3=5.5.1&cd4=5.5.1&cd2=3.5.2&ul=en-au&cid=e306b5bb-1c38-4731-974e-00bb46090ee6&aid=org.openshot.openshot-qt&cd5=Ubuntu-16.04-xenial&aip=1&tid=UA-4381101-5&t=screenview&av=2.1.0-dev1', 'pragma': 'no-cache', 'server': 'Golfe2', 'content-type': 'image/gif', 'access-control-allow-origin': '_'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     metrics:INFO Track metric: {'status': '200', 'date': 'Wed, 12 Oct 2016 10:36:44 GMT', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'content-length': '35', 'x-content-type-options': 'nosniff', 'age': '640962', 'cache-control': 'no-cache, no-store, must-revalidate', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'content-location': 'http://www.google-analytics.com/collect?ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&sc=start&cd=launch-app&an=OpenShot+Video+Editor&cd1=0.1.2&v=1&cd3=5.5.1&cd4=5.5.1&cd2=3.5.2&ul=en-au&cid=e306b5bb-1c38-4731-974e-00bb46090ee6&aid=org.openshot.openshot-qt&cd5=Ubuntu-16.04-xenial&aip=1&tid=UA-4381101-5&t=screenview&av=2.1.0-dev1', 'pragma': 'no-cache', 'server': 'Golfe2', 'content-type': 'image/gif', 'access-control-allow-origin': '_'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     ui_util:INFO Initializing UI for MainWindow
     ui_util:INFO Binding event MainWindow:actionNew_trigger
     ui_util:INFO Binding event MainWindow:actionOpen_trigger
     ui_util:INFO Binding event MainWindow:actionSave_trigger
     ui_util:INFO Binding event MainWindow:actionUndo_trigger
     ui_util:INFO Binding event MainWindow:actionSaveAs_trigger
     ui_util:INFO Binding event MainWindow:actionImportFiles_trigger
     ui_util:INFO Binding event MainWindow:actionImportImageSequence_trigger
     ui_util:INFO Binding event MainWindow:actionRedo_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveClip_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveTransition_trigger
     ui_util:INFO Binding event MainWindow:actionExportVideo_trigger
     ui_util:INFO Binding event MainWindow:actionUploadVideo_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrack_trigger
     ui_util:INFO Binding event MainWindow:actionPreferences_trigger
     ui_util:INFO Binding event MainWindow:actionPlay_trigger
     ui_util:INFO Binding event MainWindow:actionJumpStart_trigger
     ui_util:INFO Binding event MainWindow:actionRewind_trigger
     ui_util:INFO Binding event MainWindow:actionFastForward_trigger
     ui_util:INFO Binding event MainWindow:actionJumpEnd_trigger
     ui_util:INFO Binding event MainWindow:actionArrowTool_trigger
     ui_util:INFO Binding event MainWindow:actionSnappingTool_trigger
     ui_util:INFO Binding event MainWindow:actionAddMarker_trigger
     ui_util:INFO Binding event MainWindow:actionPreviousMarker_trigger
     ui_util:INFO Binding event MainWindow:actionNextMarker_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionFilesShowImage_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionTransitionsShowCommon_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAll_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowVideo_trigger
     ui_util:INFO Binding event MainWindow:actionEffectsShowAudio_trigger
     ui_util:INFO Binding event MainWindow:actionTimelineZoomIn_trigger
     ui_util:INFO Binding event MainWindow:actionTimelineZoomOut_trigger
     ui_util:INFO Binding event MainWindow:actionTitle_trigger
     ui_util:INFO Binding event MainWindow:actionAnimatedTitle_trigger
     ui_util:INFO Binding event MainWindow:actionFullscreen_trigger
     ui_util:INFO Binding event MainWindow:actionAbout_trigger
     ui_util:INFO Binding event MainWindow:actionThumbnailView_trigger
     ui_util:INFO Binding event MainWindow:actionDetailsView_trigger
     ui_util:INFO Binding event MainWindow:actionReportBug_trigger
     ui_util:INFO Binding event MainWindow:actionAskQuestion_trigger
     ui_util:INFO Binding event MainWindow:actionTranslate_trigger
     ui_util:INFO Binding event MainWindow:actionDonate_trigger
     ui_util:INFO Binding event MainWindow:actionHelpContents_trigger
     ui_util:INFO Binding event MainWindow:actionSimple_View_trigger
     ui_util:INFO Binding event MainWindow:actionAdvanced_View_trigger
     ui_util:INFO Binding event MainWindow:actionFreeze_View_trigger
     ui_util:INFO Binding event MainWindow:actionUn_Freeze_View_trigger
     ui_util:INFO Binding event MainWindow:actionShow_All_trigger
     ui_util:INFO Binding event MainWindow:actionProfile_trigger
     ui_util:INFO Binding event MainWindow:actionAdd_to_Timeline_trigger
     ui_util:INFO Binding event MainWindow:actionPreview_File_trigger
     ui_util:INFO Binding event MainWindow:actionRemove_from_Project_trigger
     ui_util:INFO Binding event MainWindow:actionFile_Properties_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveTrack_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveMarker_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrackAbove_trigger
     ui_util:INFO Binding event MainWindow:actionAddTrackBelow_trigger
     ui_util:INFO Binding event MainWindow:actionRemoveEffect_trigger
     ui_util:INFO Binding event MainWindow:actionSplitClip_trigger
     ui_util:INFO Binding event MainWindow:actionProperties_trigger
     ui_util:INFO Binding event MainWindow:actionRenameTrack_trigger
     ui_util:INFO Binding event MainWindow:actionUpdate_trigger
     ui_util:INFO Binding event MainWindow:actionTutorial_trigger
     ui_util:INFO Binding event MainWindow:actionAnimation_trigger
     ui_util:INFO Binding event MainWindow:actionLockTrack_trigger
     ui_util:INFO Binding event MainWindow:actionUnlockTrack_trigger
 files_model:INFO updating files model.
transition_model:INFO updating transitions model.
timeline_webview:INFO Qt Found!
timeline_webview:INFO $scope.Qt = true;
timeline_webview:INFO UpdateLayerIndex
effects_model:INFO updating effects model.
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
properties_model:INFO updating clip properties model.
 main_window:INFO InitCacheSettings
 main_window:INFO cache-mode: CacheMemory
 main_window:INFO cache-limit-mb: 250
 main_window:INFO Creating CacheMemory object with 262144000 byte limit
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/local/bin/openshot-qt", line 9, in <module>
      logger:ERROR load_entry_point('openshot-qt==2.1.0.dev1', 'gui_scripts', 'openshot-qt')()
      logger:ERROR   File "/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/launch.py", line 70, in main
      logger:ERROR app = OpenShotApp(sys.argv)
      logger:ERROR   File "/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/classes/app.py", line 157, in **init**
      logger:ERROR self.window = MainWindow(mode)
      logger:ERROR   File "/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/windows/main_window.py", line 1923, in **init**
      logger:ERROR self.InitCacheSettings()
      logger:ERROR   File "/usr/local/lib/python3.5/dist-packages/openshot_qt-2.1.0.dev1-py3.5.egg/openshot_qt/windows/main_window.py", line 1811, in InitCacheSettings
      logger:ERROR new_cache_object = openshot.CacheMemory(cache_limit)
      logger:ERROR AttributeError
      logger:ERROR :
      logger:ERROR module 'openshot' has no attribute 'CacheMemory'
     version:INFO Found current version: {'status': '200', 'server': 'Apache/2.2.22 (Ubuntu)', 'transfer-encoding': 'chunked', 'date': 'Wed, 19 Oct 2016 20:49:35 GMT', 'content-location': 'http://www.openshot.org/version/json/', 'content-type': 'application/json'} (b'{"openshot_version": "2.1.0"}')

Had to press CTRL-C

^C      logger:ERROR Exception ignored in:
      logger:ERROR <module 'threading' from '/usr/lib/python3.5/threading.py'>
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
      logger:ERROR t.join()
      logger:ERROR   File "/usr/lib/python3.5/threading.py", line 1054, in join
      logger:ERROR self._wait_for_tstate_lock()
      logger:ERROR   File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
      logger:ERROR elif lock.acquire(block, timeout):
      logger:ERROR KeyboardInterrupt

**Comment by ankitpati** [comment]
Can you please try the latest stable [AppImage](http://github.com/OpenShot/openshot-qt/releases/download/v2.2.0/OpenShot-v2.2.0-x86_64.AppImage "OpenShot 2.2")?

OpenShot currently works fine on Ubuntu 16.04.

Closing as stale, as there has been no activity for a while on this issue.

**Comment by clockworkpc** [comment]
Thanks, will try.
